[ADDED] - Gson Ext. Func. Added.
mobven/Extensify pull request #13
Opened 2022-06-28 13:58 UTC by ardakazanci-mobven

2022-06-29 11:18 UTC, tugfeivecek-mobven approved these changes

2022-06-30 07:21 UTC, ghost commented on extension/src/main/java/com/mobven/extension/GsonExt.kt
> +fun SharedPreferences.putObject(key: String, obj: Any?) {
These are not a gson ext. Create new file like PreferencesExt.kt

2022-06-30 07:24 UTC, abalta-mobven commented on extension/src/main/java/com/mobven/extension/IntentExt.kt
> +        applicationId.contains(".stage") -> applicationId.dropLast(6)
I think, these variants need to be generic. It could be getProductionApplicationId(variant: String, dropLast: Int)

2022-06-30 07:26 UTC, abalta-mobven commented on extension/src/main/java/com/mobven/extension/IntentExt.kt
> +fun Context?.openGoogleMaps(query: String, placeId: String) {
Add some example to sample app this and following extensions.

2022-06-30 07:26 UTC, abalta-mobven commented on extension/src/main/java/com/mobven/extension/IntentGetExtraExt.kt
> +fun Intent.getIntExtra(name: String): Int? {
These are also IntentExt, not need to create new ext file.

2022-06-30 07:29 UTC, abalta-mobven requested changes
Update ReadMe for new extensions.

2024-12-27 08:46 UTC, closed without merging